### ISSUE TITLE
Query dbt

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#11]
![Screen Shot 2020-10-07 at 11 13 33 AM](https://user-images.githubusercontent.com/69832828/95298212-58eede00-0899-11eb-9e99-6e54a4d7230c.png)

Ee query manasilayila..

**Comment by guardianangel0507** [comment]
Join Queries
This is much advanced and these are the SQL nightmares I always told you. Consider tbr_colorVariants and tb_vehicles as two SETS in mathematics. Remember Venn Diagram? In that, when we do intersection, elements which are common to both sets are returned. 
This is first done on tbr_colorVariants and tb_colors which have common colorIDs in both tables.
Then we added another intersection to the previous result by specifying the intersection condition after 'ON' as crv.vehicleID = tv.vehicleID, which means, those records which have same IDs in ColorVariants and Vehicles table are returned.
