### ISSUE TITLE
admin-route.php

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#13]
![Screen Shot 2020-10-08 at 9 27 02 AM](https://user-images.githubusercontent.com/69832828/95413211-78910f80-0948-11eb-8f03-ef1b9e984a3a.png)

Nik ee section manasilayila

admin authorized anekil userData session set cheyum nnano ? 
$uri ilek nganeya value pone
$uri value preg matched ..if match goes to approve.php right ?
pine that switch case ilek $uri check cheyunu ..angane aano

This section is full confusion for me

**Comment by guardianangel0507** [comment]
First doubt, if admin is authorized, then set the value in $_SESSION['userData'] to $userData variable, if not authorized, redirect to home-route.php. 
Check the Authentication.php class file for the function definition of isAuthorized(). You should have found it out yourself, as the $auth is an object of Authentication Class, declared just above those statements.

Boo, I think you aren't yet thinking programmatically. So think and find answers for the following questions.
The getFinalUrl() is a helper utility function, which is a user defined function. Check helpers.php file.

Now, questions:
1. What exactly does 'header()' function do?
2. While server is in php runtime, it encountered an if statement and inside the if there is a redirection, will it come back to the same script after the redirection?
3. If a php runtime is redirected to another file, then will it run the code after the redirection?

If needed, use tester.php for finding answers.
If you couldn't even after thinking, I will answer, don't worry.

**Comment by bee0507** [comment]
That ! mark is what is confusing me
I mean direct ayit $auth check cheythit value insert cheyan patule ?

that getFinalUrl function manasilayila 

preg_match("/[^\/]+$/", $parsedUrl['path'], $matches); 
Ithoke nthona..All these are soo tough for me to understand ya

Those qstns - header() function il specify cheythekuna pathilek povum le ? 
Redirection indel thirich varula to the same script after redirection 
3rd qstn manasilayila

**Comment by guardianangel0507** [comment]
Read that statement like this:
if not(!) isAuthorized()  redirect, if isAuthorized() set userData.
preg_match("/[^/]+$/", $parsedUrl['path'], $matches);

it's a pattern, I told you yesterday, "^" checks for the start pattern. $ is for the end.
that pattern just checks whether the uri starts with"/" or not and return the last word that starts and ends with "/".
$matches is an array which stores the matched value at its 0th index.

3rd Question, in that "if" statement, we redirected to approve.php. And you know that it won't redirect back. So will it run the code after that header() function, I mean, if the runtime enters that "if" statement, then will it run the switch()?

**Comment by bee0507** [comment]
Okay it wont run the switch. ipo manasilayi
