### ISSUE TITLE
admin-lander

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#14]
![Screen Shot 2020-10-08 at 9 39 16 AM](https://user-images.githubusercontent.com/69832828/95413949-58625000-094a-11eb-9dc9-52383b3cb156.png)

aa button click cheyumbo engoteka ponde ? /public/admin ..ith folder ale.. apo admin folder il eth file load avum? 
pine aa .htaccess ..ath ntha help cheyane

**Comment by guardianangel0507** [comment]
The address end path of that url is 'admin' right, so check admin-route.php, and find the switch case which matches with 'admin'.

.htaccess is used to redirect all url requests to "admin-route.php" in admin folder. If you check other public folders, there also you can find these .htaccess files, which corresponds to each folders "-route.php" files

**Comment by bee0507** [comment]
Sathyam paranja... Adyam me logic padikanam nnale..ithoke manasilavulu. I am thinking som other way I think. I was wondering why using multiple pages to get to a single page. like admin-home to admin-lander to admin-route avdenu split to admin-panel nd on. 

Alla admin-route il vanal in which situation will that preg_match work. Any url path starting with approve-manufacturer/dealer right. Ath ngane admin-route ilek varm

**Comment by guardianangel0507** [comment]
For that is what we uses the .htaccess file. 
Check that file. There are some statements starting "Redirect". They redirects every request to the admin-route.php

Now, multiple files for Single Page doubt, actually, there is only one single file, which acts as a direction layer, which directs the php runtime to different pages, which is the admin-route.php.

Admin route is used to redirect to different other php pages. It is not just to match and redirect approve-manufacturer/dealer. 

The case there is, if in case an approve request is came, then redirect to approve.php, that's all. If there is no match for pregmatch, then it wont enter that "if" statement block, and continues to the switch. If there is a pregmatch, then it will enter the if block and redirects to approve.php and returns back to "approve-users", which will also come to admin-route and displays according to the switch statement

**Comment by bee0507** [comment]
![Screen Shot 2020-10-07 at 1 14 43 PM](https://user-images.githubusercontent.com/69832828/95419027-57372000-0956-11eb-9d30-b5f372203c7d.png)
ithil approve-users click cheytha approve-users.php ilek ale ponde ?

**Comment by guardianangel0507** [comment]
yes, but the working is little different.
When you click that button, it will request the uri "approve-users", which will be redirected to admin-route.php. Then admin-route will findout the final uri, that is "approve-users", and then uses the Template Class to display approve-users.php file. All these are inside the switch case.

**Comment by bee0507** [comment]
uri "approve-users", which will be redirected to admin-route.php

athenganeya admin-route ilek pone. .htacess ?

**Comment by guardianangel0507** [comment]
yes, because of .htaccess.
.htaccess tells the server that all those requests coming inside public/admin folder should be redirected to admin-route.php

**Comment by bee0507** [comment]
![Screen Shot 2020-10-07 at 1 14 51 PM](https://user-images.githubusercontent.com/69832828/95420962-0b867580-095a-11eb-88e6-10c5f6e759ac.png)
nik inganeya varane when clicking button approve-users

**Comment by guardianangel0507** [comment]
created .htaccess inside admin folder?

**Comment by guardianangel0507** [comment]
> ![Screen Shot 2020-10-07 at 1 14 51 PM](https://user-images.githubusercontent.com/69832828/95420962-0b867580-095a-11eb-88e6-10c5f6e759ac.png)
> nik inganeya varane when clicking button approve-users

Show the Address bar of the browser

**Comment by bee0507** [comment]
> created .htaccess inside admin folder?
yup

![approv](https://user-images.githubusercontent.com/69832828/95421837-d9761300-095b-11eb-8aab-23b90161d284.png)

**Comment by guardianangel0507** [comment]
show me the folder in which htdocs is present

**Comment by bee0507** [comment]
> show me the folder in which htdocs is present

![Screen Shot 2020-10-08 at 12 03 43 PM](https://user-images.githubusercontent.com/69832828/95423215-56a28780-095e-11eb-81db-4475fd09380d.png)

**Comment by guardianangel0507** [comment]
No ya, htdocs folder. the xampp installation folder

**Comment by bee0507** [comment]
![Screen Shot 2020-10-08 at 12 12 57 PM](https://user-images.githubusercontent.com/69832828/95424038-ae8dbe00-095f-11eb-8d9c-052fef326582.png)

**Comment by guardianangel0507** [comment]
now "etc" folder

**Comment by bee0507** [comment]
![Screen Shot 2020-10-08 at 12 23 41 PM](https://user-images.githubusercontent.com/69832828/95424931-1abcf180-0961-11eb-8743-828be2007b62.png)

**Comment by guardianangel0507** [comment]
next "extra" folder

**Comment by bee0507** [comment]
![Screen Shot 2020-10-08 at 12 29 40 PM](https://user-images.githubusercontent.com/69832828/95425533-0d543700-0962-11eb-8abf-1c4c00ca7a3f.png)

**Comment by guardianangel0507** [comment]
open httpd-vhosts.conf in vscode and show

**Comment by bee0507** [comment]
![Screen Shot 2020-10-08 at 12 33 08 PM](https://user-images.githubusercontent.com/69832828/95425775-6c19b080-0962-11eb-890f-8901615c5f4e.png)

**Comment by guardianangel0507** [comment]
Nothing to do here. Now, Inside etc folder there will be a file called httpd.conf, show that

**Comment by bee0507** [comment]
> Nothing to do here. Now, Inside etc folder there will be a file called httpd.conf, show that

Too lengthy
![Screen Shot 2020-10-08 at 12 43 37 PM](https://user-images.githubusercontent.com/69832828/95426697-f4e51c00-0963-11eb-8037-79cdcf977ccf.png)

**Comment by guardianangel0507** [comment]
We don't need everything

Before proceeding, make a copy of the file.
then edit the original as mentioned as below
check for this line:
LoadModule rewrite_module modules/mod_rewrite.so

if it has a preceding "#", remove it.

then find this:
```
<Directory />
    AllowOverride none
    Require all denied
</Directory>

```
and edit it to

```
<Directory />
  Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

**Comment by guardianangel0507** [comment]
Small Mistake

**Comment by guardianangel0507** [comment]
> We don't need everything
> 
> Before proceeding, make a copy of the file.
> then edit the original as mentioned as below
> check for this line:
> LoadModule rewrite_module modules/mod_rewrite.so
> 
> if it has a preceding "#", remove it.
> 
> then find this:
> 
> ```
> <Directory />
>     AllowOverride none
>     Require all denied
> </Directory>
> ```
> 
> and edit it to
> 
> ```
> <Directory />
>   Options Indexes FollowSymLinks
>         AllowOverride All
>         Require all granted
> </Directory>
> ```

Check the comment now

**Comment by bee0507** [comment]
Ok did

**Comment by guardianangel0507** [comment]
Now restart apache in xampp and to go to that approve-users again

**Comment by bee0507** [comment]
still not working..

**Comment by guardianangel0507** [comment]
What's showing now? in the browser?

**Comment by guardianangel0507** [comment]
LoadModule rewrite_module modules/mod_rewrite.so

Did this had "#" at the start?

**Comment by bee0507** [comment]
> LoadModule rewrite_module modules/mod_rewrite.so
> 
> Did this had "#" at the start?

Nop

same showng
![Screen Shot 2020-10-08 at 2 13 47 PM](https://user-images.githubusercontent.com/69832828/95435783-9ffbd280-0970-11eb-9120-e2d6d390132e.png)

**Comment by guardianangel0507** [comment]
`ServerName localhost:`

what is the value of this?

**Comment by guardianangel0507** [comment]
Look for the following and make it as same as the below:
then restart apache again. and try

```
DocumentRoot "C:/xampp/htdocs"
<Directory "C:/xampp/htdocs">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks Includes ExecCGI

    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    #
    AllowOverride All

    #
    # Controls who can get stuff from this server.
    #
    Require all granted
</Directory>
```

**Comment by guardianangel0507** [comment]
Don't change the Directory  and DocumentRoot

**Comment by bee0507** [comment]
> Look for the following and make it as same as the below:
> then restart apache again. and try
> 
> ```
> DocumentRoot "C:/xampp/htdocs"
> <Directory "C:/xampp/htdocs">
>     #
>     # Possible values for the Options directive are "None", "All",
>     # or any combination of:
>     #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
>     #
>     # Note that "MultiViews" must be named *explicitly* --- "Options All"
>     # doesn't give it to you.
>     #
>     # The Options directive is both complicated and important.  Please see
>     # http://httpd.apache.org/docs/2.4/mod/core.html#options
>     # for more information.
>     #
>     Options Indexes FollowSymLinks Includes ExecCGI
> 
>     #
>     # AllowOverride controls what directives may be placed in .htaccess files.
>     # It can be "All", "None", or any combination of the keywords:
>     #   AllowOverride FileInfo AuthConfig Limit
>     #
>     AllowOverride All
> 
>     #
>     # Controls who can get stuff from this server.
>     #
>     Require all granted
> </Directory>
> ```

Its same

**Comment by guardianangel0507** [comment]
Ook boo,
Download Teamviewer and install it in your lap.
then Evening after 6 pm, put a comment here.
and paste what is it in your teamviewer like the one below in that comment

**Comment by bee0507** [comment]
Noo evening not possbile, tommorw will do

**Comment by guardianangel0507** [comment]
Ook, just comment here when you are ready. No problem 😂

**Comment by bee0507** [comment]
Nee free avumbo mathi. I will be free till 4.30

1534849375

**Comment by guardianangel0507** [comment]
Lets do now

**Comment by guardianangel0507** [comment]
send the latest password

**Comment by guardianangel0507** [comment]
The password will change over time

**Comment by guardianangel0507** [comment]
And Dont close teamviewer

**Comment by bee0507** [comment]
Not safe now. Later. Maybe tmw

**Comment by guardianangel0507** [comment]
Ook, then let's do on saturday or sunday. Tomorrow also me have Training Boo.

**Comment by bee0507** [comment]
Ok fine boo

**Comment by bee0507** [comment]
> Ook, then let's do on saturday or sunday. Tomorrow also me have Training Boo.

Or boo, lets do after my internals are over. I need to study for it this weekend..

**Comment by guardianangel0507** [comment]
Sure boo.
Let's do after. No problem.

**Comment by bee0507** [comment]
Ook sett boo
