### ISSUE TITLE
javascript codes optimized ?

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#3]
![Screen Shot 2020-08-25 at 3 38 17 PM](https://user-images.githubusercontent.com/69832828/91726839-8374b980-ebbe-11ea-88b8-6ce8a0e60667.png)

Whats this ?

**Comment by guardianangel0507** [comment]
Green are Added codes, Red are modified codes or deleted codes, check the + and - signs

**Comment by guardianangel0507** [comment]
Also, don't look at these .xml files, they are editor configs.never mind. project files will always be in css, js, html and php
